### ISSUE TITLE
advice on reporting models

### ISSUE THREAD

**Issue by TimLanglois** [beckyfisher/FSSgam#5]
@beckyfisher What advice can we give on when to report a top model or not?
For example - if a model explains <10% variance should it it even be reported in a table?

**Comment by TimLanglois** [comment]
This is maybe another argument for have importance scores multiplied by r2?

**Comment by beckyfisher** [comment]
Hi Tim,
R square is a slippery beast for non-gaussian mixed models in particular, and especially if you are using bs=re specification for your random effects (such as when using tw() and gam). In that case much of the explained variance may just be due to the random effects, with the fixed part of the model being relatively un-informative (although I did provide the unique R square option, I havn't really tested how reliable that is). I tend to ignore R square entirely and go with model weights and/or the within 2AICc principle of parsimony. If a model has a low R square but is still selected by AICc with a high weight over the NULL fit, then we can infer that the variables in the model are worth reporting on regardless of R square.
